lv-lib-png: add wayland to REQUIRED_DISTRO_FEATURES
[Martin Jansa]

* fixes:
ERROR: Nothing PROVIDES 'lvgl' (but meta-oe/recipes-graphics/lvgl/lv-lib-png_8.0.2.bb DEPENDS on or otherwise requires it)
lvgl was skipped: missing required distro feature 'wayland' (not in DISTRO_FEATURES)
ERROR: Nothing RPROVIDES 'lv-lib-png-dev' (but meta-oe/recipes-graphics/lvgl/lv-lib-png_8.0.2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lv-lib-png-dev'
NOTE: Runtime target 'lv-lib-png-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lv-lib-png-dev']
ERROR: Nothing RPROVIDES 'lv-lib-png' (but meta-oe/recipes-graphics/lvgl/lv-lib-png_8.0.2.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lv-lib-png'
NOTE: Runtime target 'lv-lib-png' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lv-lib-png']

[Philippe Coval]

Port patch from upstream, beside dunfell notation,
recipes are now aligned.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Author: Martin Jansa <Martin.Jansa@gmail.com>
Origin: https://lists.openembedded.org/g/openembedded-devel/message/93498Relate-to: https://github.com/openembedded/meta-openembedded/pull/454
Relate-to: https://github.com/lvgl/lvgl/issues/2534
Forwarded: https://booting.oniroproject.org/distro/oniro/-/merge_requests/432
Last-Update: 2021-11-17
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>